### ISSUE TITLE
Implement MuSig2 for N-of-N addresses

### ISSUE THREAD

**Issue by ekrembal** [chainwayxyz/clementine#116]

**Comment by ekrembal** [comment]
This MuSig2 can be used as a internal key of the taproot address to reduce costs

**Comment by ekrembal** [comment]
See: [https://github.com/conduition/musig2/blob/84172ee7794405fb995825fea38f7c6f0c111339/src/rounds.rs#L251](https://github.com/conduition/musig2/blob/84172ee7794405fb995825fea38f7c6f0c111339/src/rounds.rs#L251)

**Comment by ozankaymak** [comment]
Outdated
