### ISSUE TITLE
Compiling Takes Long Time and Uses Excessive Amount of Memory

### ISSUE THREAD

**Issue by ceyhunsen** [chainwayxyz/clementine#162]
### Issue Description

Compiling any target, like tests or a specific binary, takes a very long time and consumes high memory. Sometimes, my machine with 16 GB RAM fails to compile (OS kills both processes because of the OOM) because of high memory usage (100% of the 16 GB). This happens when VS Code's Rust Analyzer and Cargo working together. This is a typical scenario and a typical environment for a developer and this should not be acceptable for a cli program.

I guess this issue probably caused by the multiple binary targets. In that case, a different approach should be proposed to solve this issue, for the sake of my (or possibly others) sanity. I don't have any proposal right now, though.

It also might be caused by VS Code's configuration. In that case, we might put a default local configuration (`.vscode`) to repo itself. Don't think this is the reason though.

Let's fix this, pls.

### Tasks

Parts of the task:

- [ ] Make sure what makes both VS Code and Cargo consumes excessive amount of memory and time
- [ ] Propose a solution
- [ ] Implement that solution

### Deadline of the Issue

2024

**Comment by eyusufatik** [comment]
Welcome to the world of Rust :)

A few takeaways from Citrea's repository.

Use somthing like `cargo udeps` to remove unused dependencies in Cargo.toml's.

If you're using any library which have build scripts, they might be compiling a C library on every compilation. (RocksDb rust  lib does that for instance) Which is not really ideal. These libararies ususally have a flag to dynamically link the library from your system so you dont have to recompile them.

**Comment by ceyhunsen** [comment]
Thanks @eyusufatik. I am still looking at and researching the causes you mentioned.

Small update about the issue: We have multiple binary files that does simple things, like starting an operator server. This binary file currently takes 249M of space. Other binary files also takes same amount of space. Probably static linking causes this. As Esad suggested, we can look in to dynamic linking with 3rd party libraries. Or maybe just configure them to not full featured and smaller form factor.

I have another proposal though: Have one binary that takes arguments which matches to current binaries. This can help reduce compiling resource consumption significantly. And it can really help distributing the software, simply because we need one binary to distribute. I will be opening an issue soon, that details this solution.

**Comment by ceyhunsen** [comment]
Looks like [jsonrpsee](https://github.com/paritytech/jsonrpsee) causes binaries to get bigger. To use this library, huge 3rd party libraries are included in the binary (like Tokio).

This will cause binaries to get 3 times bigger and long compile times. Not sure if this can be fixed by using another library for JSON RPC or it is inevitable.

I encountered same issue with [bitcoin-mock-rpc](https://github.com/chainwayxyz/bitcoin-mock-rpc) after including jsonrpsee to dependencies.

**Comment by ceyhunsen** [comment]
This issue is marked as closed by #305. But it should be noted that that PR didn't really fixed this problem drastically. It is assumed that this behavior is expected for the amount of dependencies Clementine has.

Can be closed after dev is merged with main.
