### ISSUE TITLE
Crate Reorganization

### ISSUE THREAD

**Issue by ceyhunsen** [chainwayxyz/clementine#167]
### Proposal Description

# Description

Moving every crate to a common directory is considered a good practice. We should move `core`, `circuits` and `risc0-guest` to the new `crates` directory.

This is a big move and probably will break every open PR out there. I think we should open a PR about this and move everything to `crates` directory once every open PR is closed.

If this suggestion is a go, we shouldn't wait much. Because every PR complicates code and it is harder for us to change the structure.

**Comment by ekrembal** [comment]
Let's keep it as is
