### ISSUE TITLE
Problems with database

### ISSUE THREAD

**Issue by ceyhunsen** [chainwayxyz/clementine#168]
### Proposal Description

Some tests fails because of some other test running in parallel tries to access and modify the data needed by current test. This does not happen in final binaries but only in tests. We should reorganize our database so every test can have an isolated database environment. So that we can open the possibility to run every test in parallel.

Current database tries to convert every structure to a `String` and writes it to database that way. To read it, a new structure is created with read `String`. This is a performance bottleneck and not a very ideal way of doing this. We should find better ways of doing this.

This issue only describes problems briefly and given solutions are not final. They can be altered later.

**Comment by ekrembal** [comment]
#169 is also a blocker for tests running in parallel

**Comment by ozankaymak** [comment]
Done, closing.
