### ISSUE TITLE
Remove code duplication in calculating move_reveal tx twice

### ISSUE THREAD

**Issue by ekrembal** [chainwayxyz/clementine#220]
### Issue Description

https://github.com/chainwayxyz/clementine/blob/ekrem/new-architecture/core/src/verifier.rs#L202
https://github.com/chainwayxyz/clementine/blob/ekrem/new-architecture/core/src/verifier.rs#L314
Same code in these two

**Comment by ozankaymak** [comment]
We have to do code duplication by the design, so I am closing this issue.
