### ISSUE TITLE
Operator withdrawal function

### ISSUE THREAD

**Issue by ekrembal** [chainwayxyz/clementine#221]

**Comment by ozankaymak** [comment]
Operator needs to handle its logic for finding the root transaction for the kickoff_utxo in the funding chain as mentioned [here](https://github.com/chainwayxyz/clementine/pull/222#issuecomment-2293330523).

**Comment by ekrembal** [comment]
Operators will also need to read all kickoff_txs from the verifier's db, so an operator should also run a verifier as well

**Comment by ekrembal** [comment]
Completed with #253
