### ISSUE TITLE
Improve database

### ISSUE THREAD

**Issue by ozankaymak** [chainwayxyz/clementine#280]
### Proposal Description

While this database is well-working for Rust tests, it is very flaky and sometimes leads to unexpected errors when it is tested e2e. Its concurrency and atomicity must be improved.

**Comment by ekrembal** [comment]
- make get_unused_kickoff_utxo_and_increase_idx atomic
- make save_kickoff_utxos atomic
- make save_sighashes_and_get_nonces atomic

**Comment by ekrembal** [comment]
save operators kickoff_utxo sig to the table

**Comment by ozankaymak** [comment]
Closed by #283 .
