### ISSUE TITLE
Add natspec to contracts and write better tests for deposit/withdraw

### ISSUE THREAD

**Issue by okkothejawa** [chainwayxyz/clementine#98]
### Issue Description

Contracts lacks natspec at the moment and the tests can be improved by accepting random transaction data instead of hardcoded ones. Merkle tree related testing can be improved by removing the assertions against hardcoded values and by doing differential testing against another merkle tree implementation instead.

### Tasks

Parts of the task:
- [x] #109
- [ ] Better tests

### Deadline of the Issue

Before open sourcing of the repo

**Comment by ozankaymak** [comment]
Done, closing.
